## creamos una imagen de docker compose que contenga sql server
## se crea la imagen del editor visual
version: '3.7'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./backup:/var/opt/mssql/backup
    restart: always
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080